# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "SYtW2B/OShcV6WoiNj7TABW4ArKtPpDYjDnKOAN62K6GIF+6Z5iYe/kvBKmyq/oZQcJ/6UO9hLMOEgoXmRXwQ4Vz++/RMoHKfQ0M0ni0oLZlFzHBFwDWAm7Cwvm7czyQNb4EGUtTBKNlSTd/XKWveHK2NlPpl/oBZ9vjcEeWSuZdvtu6c3ptPihN6lM7bfUKX406W009uvdhCTzoJldRMok3C97cpRtLnlpJbL3XconuHRHQZ12Nwne2fZiRJ8QYmDCk1q2rfRENCPov5GxWPxYe1EFHLR8Wtq00Cp/4aCeqOnzZdMXT7a4GpkJb/OPs2NWhd1Yp6y1nv8fhgNF8nxjGiFyXUnn03+vlHGmWWOTee1k694lzoM7aRP9QcC0KaEGPjEMaZdkCD0rwC7zdx60tsVIBAWWC525gkM22+WTRiMC7strecoJP2E8/IBTHLdlFFsIZH9K6Zwtj1SM/vmC2NuYlCpp8xXxkLcdEBv25frcgNWNB0s6V+nPOc4OLZ1nY9YcgI+woPAMHEm9XwsR8xPrb35mFOy84EK/AgjRy/vaxSgQQAxf4tMLkv07wV2yzXbPXDcIST6p/vaauMKPyOpGjkMd0zQqPjMekZXPkI6NmaoCctU1eStKBeL3GdmllhTeuS2Tp6zd1HpT4YE3yajKsjiJIYXGVBatS2Zc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels guyer
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe guyer --channel=main
